version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: yarn run start-watch
  frontend:
    extends:
      service: base-app
    ports:
      - 3000:3000
    volumes:
      - node_modules:/code/node_modules
      - .:/code

volumes:
  node_modules:
